In [ ]:
import numpy as np
import pandas as pd

from urllib.request import urlopen
from bs4 import BeautifulSoup

In [ ]:
def getHTMLContent(link):
    html = urlopen(link)
    soup = BeautifulSoup(html, 'html.parser')
    return soup

In [ ]:
content = getHTMLContent('https://en.wikipedia.org/wiki/List_of_countries_and_dependencies_by_population')
tables = content.find_all('table')
for table in tables:
    print(table.prettify())

<table class="wikitable sortable" style="text-align:right">
 <tbody>
  <tr class="is-sticky">
   <th>
   </th>
   <th style="width:17em">
    <a href="/wiki/List_of_sovereign_states" title="List of sovereign states">
     Country
    </a>
    /
    <a href="/wiki/Dependent_territory" title="Dependent territory">
     Dependency
    </a>
   </th>
   <th>
    Population
   </th>
   <th style="width:2em">
    % of
    <br/>
    world
   </th>
   <th>
    Date
   </th>
   <th>
    <span class="nowrap">
     Source (official or from
    </span>
    <br/>
    the
    <a href="/wiki/United_Nations" title="United Nations">
     United Nations
    </a>
    )
   </th>
   <th class="unsortable">
   </th>
  </tr>
  <tr>
   <th>
    –
   </th>
   <td style="text-align:left">
    <b>
     World
    </b>
   </td>
   <td>
    <b>
     8,073,454,000
    </b>
   </td>
   <td>
    <b>
     100%
    </b>
   </td>
   <td>
    <b>
     <span data-sort-value="000000002023-11-24-0000" style="white-space:nowra

In [ ]:

# The cell with the country name for each row includes a link to the country webpage on Wikipedia
table = content.find('table', {'class': 'wikitable sortable'})
rows = table.find_all('tr')

# List of all links
for row in rows:
    # print(row)
    cells = row.find_all('td')

    if len(cells) > 1:
        try:

            country_link = cells[0].find('a')
            if country_link.get('href').find('Demographics'):
                print(country_link.get('href')[22:])
                a = 0
        except:
            pass

China
India
the_United_States
Indonesia
Pakistan
Nigeria
Brazil
Bangladesh
Russia
Mexico
Japan
the_Philippines
Ethiopia
Egypt
Vietnam
the_Democratic_Republic_of_the_Congo
Iran
Turkey
Germany
France
e_United_Kingdom
Thailand
Tanzania
South_Africa
Italy
Myanmar
Colombia
South_Korea
Spain
Kenya
Argentina
Algeria
Sudan
Uganda
Iraq
Ukraine
nada
Poland
Morocco
Uzbekistan
Saudi_Arabia
Yemen
Peru
Angola
Malaysia
Afghanistan
Mozambique
Ghana
Ivory_Coast
Nepal
Venezuela
Madagascar
stralia
North_Korea
Cameroon
Niger
Taiwan
Mali
Burkina_Faso
Sri_Lanka
Syria
Malawi
Chile
Kazakhstan
Zambia
Romania
Ecuador
e_Netherlands
Somalia
Senegal
Guatemala
Chad
Cambodia
Zimbabwe
South_Sudan
Guinea
Rwanda
Burundi
Benin
Bolivia
Tunisia
Belgium
Haiti
Jordan
Cuba
the_Czech_Republic
the_Dominican_Republic
Sweden
Greece
Portugal
Azerbaijan
Israel
Hungary
Honduras
Tajikistan
the_United_Arab_Emirates
Belarus
Papua_New_Guinea
Austria
Switzerland
Sierra_Leone
Togo
Paraguay
Laos
Hong_Kong
Kyrgyzstan
El_Salvador
Libya
Serb

In [ ]:
def getAdditionalDetails(url):
    try:
        country_page = getHTMLContent('https://en.wikipedia.org/wiki/' + url)
        # print(country_page)
        table = country_page.find('table', {'class': 'infobox ib-country vcard'})
        additional_details = []
        read_content = False
        for tr in table.find_all('tr'):
            if (tr.get('class') == ['mergedtoprow'] and not read_content):
                link = tr.find('a')
                if (link and (link.get_text().strip() == 'Area' or
                   (link.get_text().strip() == 'GDP' and tr.find('span').get_text().strip() == '(nominal)'))):
                    read_content = True
            elif ((tr.get('class') == ['mergedrow'] or tr.get('class') == ['mergedbottomrow']) and read_content):
                additional_details.append(tr.find('td').get_text().strip('\n'))
                if (tr.find('div').get_text().strip() != '•\xa0Total area' and
                   tr.find('div').get_text().strip() != '•\xa0Total'):
                    read_content = False
                    print("IF:",tr.find('div').get_text().strip())
                else:
                    print("ELSE:",tr.find('div').get_text().strip(),read_content)
        return additional_details
    except Exception as error:
        print('Error occured: {}'.format(error))
        return []

In [ ]:
data_content = []
for row in rows:
    cells = row.find_all('td')
    if len(cells) > 1:
        try:
            country_link = cells[0].find('a')
            country_info = [cell.text.strip('\n') for cell in cells]
            print(country_info)
            if country_link.get('href').find('Demographics'):
                additional_details = getAdditionalDetails(country_link.get('href')[22:])

            else:
                additional_details = getAdditionalDetails(country_link.get('href'))

            if (len(additional_details) == 4):
                country_info += additional_details
                data_content.append(country_info)
        except:
            pass


dataset = pd.DataFrame(data_content)

['–', 'World', ' 8,033,777,000', '100%', '2 Jun 2023', 'UN projection[3]', '']
['\xa0China', '1,411,750,000', '17.6%', '31 Dec 2022', 'Official estimate[4]', '[b]']
ELSE: • Total True
IF: • Water (%)
ELSE: • Total True
IF: • Per capita
['\xa0India', '1,392,329,000', '17.3%', '1 Mar 2023', 'Official projection[5]', '[c]']
ELSE: • Total True
IF: • Water (%)
ELSE: • Total True
IF: • Per capita
['\xa0United States', '334,834,000', '4.17%', '2 Jun 2023', 'National population clock[7]', '[d]']
ELSE: • Total area True
IF: • Water (%)
ELSE: • Total True
IF: • Per capita
['\xa0Indonesia', '277,749,853', '3.46%', '31 Dec 2022', 'Official estimate[8]', '']
IF: • Land
ELSE: • Total True
IF: • Per capita
['\xa0Pakistan', '239,017,494', '2.98%', '30 Apr 2023', 'UN projection[3]', '[e]']
ELSE: • Total True
IF: • Water (%)
ELSE: • Total True
IF: • Per capita
['\xa0Nigeria', '218,541,000', '2.72%', '1 Jul 2022', 'UN projection[3]', '']
ELSE: • Total True
IF: • Water (%)
ELSE: • Total True
IF: • Per cap

In [ ]:
dataset

0              1          2            3  \
0             China  1,411,750,000      17.6%  31 Dec 2022   
1             India  1,392,329,000      17.3%   1 Mar 2023   
2     United States    334,834,000      4.17%   2 Jun 2023   
3          Pakistan    239,017,494      2.98%  30 Apr 2023   
4           Nigeria    218,541,000      2.72%   1 Jul 2022   
..              ...            ...        ...          ...   
181      San Marino         33,847  0.000421%  30 Apr 2023   
182           Palau         16,733  0.000208%   1 Jul 2021   
183    Cook Islands         15,040  0.000187%   1 Jul 2021   
184           Nauru         11,832  0.000147%   1 Jul 2021   
185          Tuvalu         10,679  0.000133%   1 Jul 2021   

                                  4    5  \
0              Official estimate[4]  [b]   
1            Official projection[5]  [c]   
2      National population clock[7]  [d]   
3                  UN projection[3]  [e]   
4                  UN projection[3]        
..                              ...  ...   
181  Monthly national estimate[200]        
182                2021 Census[202]        
183                2021 Census[204]        
184  National annual projection[95]        
185  National annual projection[95]        

                                                     6                  7  \
0    9,596,961 km2 (3,705,407 sq mi)[g][5] (3rd / 4th)             2.8[h]   
1          3,287,263[2] km2 (1,269,219 sq mi)[h] (7th)                9.6   
2         3,796,742 sq mi (9,833,520 km2)[10] (3rd[c])    4.66[11] (2015)   
3             881,913 km2 (340,509 sq mi)[b][9] (33rd)               2.86   
4                   923,769 km2 (356,669 sq mi) (31st)                1.4   
..                                                 ...                ...   
181                   61.2 km2 (23.6 sq mi)[1] (191st)                  0   
182                        459 km2 (177 sq mi) (180th)         negligible   
183                  236.7 km2 (91.4 sq mi) (unranked)  15,040[4] (223rd)   
184                         21 km2 (8.1 sq mi) (193rd)               0.57   
185                       26 km2 (10 sq mi)[2] (192nd)         negligible   

                                  8                       9  
0      $19.374 trillion[i][9] (2nd)       $13,721[9] (64th)  
1         $3.737 trillion[20] (5th)      $2,601[20] (139th)  
2        $26.855 trillion[14] (1st)       $80,035[14] (7th)  
3       $376.493 billion[12] (42nd)      $1,658[11] (177th)  
4            $504 billion[5] (31st)      $2,326 [5] (145th)  
..                              ...                     ...  
181        $1.62 billion[5] (192nd)       $47,700[5] (20th)  
182                 $322 million[5]              $17,438[5]  
183  US$384 million[5] (not ranked)  US$21,994 (not ranked)  
184                 $133 million[9]              $10,125[9]  
185          $45 million[3] (194th)       $2,970[3] (118th)  

[186 rows x 10 columns]

Now, our dataset is compiled together but lacks headers for columns. Thus, we would now add those headers and remove columns that bring no value.

In [ ]:
final_dataset = dataset[[0,1,2,6,7,8,9]].copy()
final_dataset

0              1          2  \
0             China  1,411,750,000      17.6%   
1             India  1,392,329,000      17.3%   
2     United States    334,834,000      4.17%   
3          Pakistan    239,017,494      2.98%   
4           Nigeria    218,541,000      2.72%   
..              ...            ...        ...   
181      San Marino         33,847  0.000421%   
182           Palau         16,733  0.000208%   
183    Cook Islands         15,040  0.000187%   
184           Nauru         11,832  0.000147%   
185          Tuvalu         10,679  0.000133%   

                                                     6                  7  \
0    9,596,961 km2 (3,705,407 sq mi)[g][5] (3rd / 4th)             2.8[h]   
1          3,287,263[2] km2 (1,269,219 sq mi)[h] (7th)                9.6   
2         3,796,742 sq mi (9,833,520 km2)[10] (3rd[c])    4.66[11] (2015)   
3             881,913 km2 (340,509 sq mi)[b][9] (33rd)               2.86   
4                   923,769 km2 (356,669 sq mi) (31st)                1.4   
..                                                 ...                ...   
181                   61.2 km2 (23.6 sq mi)[1] (191st)                  0   
182                        459 km2 (177 sq mi) (180th)         negligible   
183                  236.7 km2 (91.4 sq mi) (unranked)  15,040[4] (223rd)   
184                         21 km2 (8.1 sq mi) (193rd)               0.57   
185                       26 km2 (10 sq mi)[2] (192nd)         negligible   

                                  8                       9  
0      $19.374 trillion[i][9] (2nd)       $13,721[9] (64th)  
1         $3.737 trillion[20] (5th)      $2,601[20] (139th)  
2        $26.855 trillion[14] (1st)       $80,035[14] (7th)  
3       $376.493 billion[12] (42nd)      $1,658[11] (177th)  
4            $504 billion[5] (31st)      $2,326 [5] (145th)  
..                              ...                     ...  
181        $1.62 billion[5] (192nd)       $47,700[5] (20th)  
182                 $322 million[5]              $17,438[5]  
183  US$384 million[5] (not ranked)  US$21,994 (not ranked)  
184                 $133 million[9]              $10,125[9]  
185          $45 million[3] (194th)       $2,970[3] (118th)  

[186 rows x 7 columns]

In [ ]:

headers = ['Country', 'Population','Percentage of World Population','Total Area', 'Percentage Water', 'Total Nominal GDP', 'Per Capita GDP']
final_dataset.columns = headers




final_dataset.to_csv("Dataset.csv", index = False)

In [ ]:
import requests
from bs4 import BeautifulSoup
import csv

In [ ]:
url="https://en.wikipedia.org/wiki/List_of_countries_and_dependencies_by_population"

In [ ]:
html_response=requests.get(url)

In [ ]:
soup=BeautifulSoup(html_response.text,'html.parser')

In [ ]:
population_table=soup.find('table',{'class':'wikitable'})

In [ ]:
#extract data
data_list=[]

In [ ]:
for row in population_table.find_all('tr')[1:]:
    columns=row.find_all(['th','td'])
    country=columns[1].text.strip()
    population=columns[2].text.strip()
    data_list.append([country,population])

In [ ]:
#open
#write mode
#with
file="population_data_retrieved.csv"

In [ ]:
with open(file,'w',newline='',encoding='utf-8') as csv_file:
    c=csv.writer(csv_file)
    c.writerow(['country','population']) #header row
    c.writerows(data_list)

In [ ]:
'''Student grade analysis
You are given a csv file (student_grades.csv) containing information about
students and their grades.The CSV file has the following columns:
student_id
Name
Math
English
Science
write a python pgm using pandas to perform following task:
1.load the csv file int a pandas dataframe
2.calculate and display the avg grade for each subject
3.Identify and display the students with highest avg grade
4.create a new column called Total representing the total grade for each student
5.Save the updated dataframe to a new csv file
Your pgm should be well docummented with comments to explain each step'''

In [ ]:
#load the csv file into a pandas dataframe
df=pd.read_csv('student_grades.csv')
#calculate and display the average grade for each subject
avg_grades=df[['Math','English','Science']].mean()
print("Average grades")
print(avg_grades)
#Identify and display the students with highest avg grade
highest_avg_student=df.loc[(df[['Math','English','Science']].mean(axis=1)==df[['Math','English','Science']].mean().max())]
print("student with Highest Average:")
print(highest_avg_student)
#create a new column called Total representing the total grade
df['Total']=df[['Math','English','Science']].sum(axis=1)
#Save the updated dataframe to a new csv file
df.to_csv('new_data.csv',index=False)

In [ ]:
'''You are given two matrices A and B represented as 2D Numpy
arrays.write a python pgm using Numpy to perform the following matrix
operations:
1.Matrix addition
2.Matrix multiplication
3.Transpose
4.Element wise operations:
a.create a new matrix C with random integer values
b.perform element wise addition,subtraction,multiplication and
division between matrix A and matrix C.print the results
'''

In [ ]:
import numpy as np

In [ ]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])

In [ ]:
C=np.random.randint(1,10,size=(2,2))

In [ ]:
#1.Matrix addition
print(A+B)

[[ 6  8]
 [10 12]]


In [ ]:
#2.Matrix multiplication
print(np.dot(A,B))

[[19 22]
 [43 50]]


In [ ]:
#Transpose
print(np.transpose(A))

[[1 3]
 [2 4]]


In [ ]:
print(A+C)

[[ 9  9]
 [10 10]]


In [ ]:
print(A-C)

[[-7 -5]
 [-4 -2]]


In [ ]:
print(A*C)

[[ 8 14]
 [21 24]]


In [ ]:
print(np.divide(A,C))

[[0.125      0.28571429]
 [0.42857143 0.66666667]]
